### ISSUE TITLE
can't extract gradients of certain images

### ISSUE THREAD

**Issue by neouyghur** [ankurtaly/Attributions#2]
Hi, I successfully extracted gradients on some images. It is a very nice job. However, It fails on some images like attached images. The gradient score has Nan value.  How can we fix it? Thanks.

![1](https://cloud.githubusercontent.com/assets/6363244/24036701/6d8193ea-0b03-11e7-8501-e1da49b27f38.jpg)
![4](https://cloud.githubusercontent.com/assets/6363244/24036704/713a88b6-0b03-11e7-8230-adb4187102a9.jpg)

**Comment by ankurtaly** [comment]
Thanks for trying out the method. I will run it on the images below.

Note that the default image size for Inception is 224*224, and therefore
the current attribution code only works for this size.

Could you try resizing the images below to 224*224?

**Comment by neouyghur** [comment]
@ankurtaly I also think it is the problem of the image size. However, some images which are not the size of 224 * 224 get the gradients. So I though it is not the problem of the size. I will try that. thanks.
