### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 175

### ISSUE THREAD

**Issue by MilesQLi** [ankurtaly/Attributions#6]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-c48fdf3979cf> in <module>()
      1 # Load the Inception model.
----> 2 sess, graph = load_model()
      3 
      4 # Load the labels vocabulary.
      5 labels = np.array(open(LABELS_LOC).read().split('\n'))

<ipython-input-2-a6d3666d440b> in load_model()
      8   cfg = tf.ConfigProto(gpu_options={'allow_growth':True})
      9   sess = tf.InteractiveSession(graph=graph, config=cfg)
---> 10   graph_def = tf.GraphDef.FromString(open(MODEL_LOC).read())
     11   tf.import_graph_def(graph_def)
     12   return sess, graph

C:\ProgramData\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 175: character maps to <undefined>

**Comment by MilesQLi** [comment]
labels = np.array(open(LABELS_LOC,"rb").read().split('\n'))

**Comment by JaeDukSeo** [comment]
why is this closed there still is a problem

**Comment by MilesQLi** [comment]
> why is this closed there still is a problem

when you replace open(LABELS_LOC) with open(LABELS_LOC,"rb"), it still won't work?
